#' @title Get survey forms
#' @description
#' Get the survey form definition for a specific survey form from SurveyCTO via API.  This form is a wrapper for `rsurveycto::scto_get_form_definitions()`.
#'
#' @param .formid a character string that identifies the SurveyCTO form
#' @param .auth an authorization block generated by `rsurveycto::scto_auth()`
#'
#' @return A list object that corresponds to the sheets of survey form from SurveyCTO, which are typically downloaded as XLSX files. Class data.frame and data.table. The list has four elements: `settings`, `choices`, `fields`, and `formulasConvertedToStaticValues`.
#' @importFrom rsurveycto scto_get_form_definitions
#' @export
#'
#' @examples NULL
scto_form <- function(.formid, .auth = auth){
  are_equal(class(.auth), "scto_auth")
  are_equal(class(.formid), "character")
  scto_get_form_definitions(auth = .auth, form_ids = .formid)
}
