#' @title Get survey data
#' @description Get the survey responses for a specific survey form from SurveyCTO via API.  This form is a wrapper for `rsurveycto::scto_read()`.
#'
#' @param .formid a character string that identifies the SurveyCTO form
#' @param .auth an authorization block generated by `rsurveycto::scto_auth()`
#'
#' @return A `data.frame` of survey responses with every column in character format. As if it were loaded from CSV with `read.csv(..., colClasses="")`.
#' @importFrom assertthat are_equal
#' @importFrom rsurveycto scto_read
#' @export
#'
#' @examples NULL
#'

## This function is a wrapper for scto_get_form_definitions
## It returns a survey dataset, which is a class data.frame and data.table
## Numeric columns are retained as characters (!)
## Tibble does not play nicely with data.table
scto_responses <- function(.formid = formid, .auth = auth){
  are_equal(class(.auth), "scto_auth")
  are_equal(class(.formid), "character")
  scto_read(auth = .auth, ids = .formid)
}
